### ISSUE TITLE
TypeError: unbound method fetch() must be called with YahooData instance as first argument (got unicode instance instead)'

### ISSUE THREAD

**Issue by bkcollection** [ericsnth/YahooData#1]
YahooData.fetch("TSLA", start="2000-01-01", end="2021-12-31")

I tried in python 2.7 and return 'TypeError: unbound method fetch() must be called with YahooData instance as first argument (got unicode instance instead)'

Do you know what changes needed for Python 2.7? I am in an old image in a cloud system and is hard for me to upgrade to python 3. Thanks

**Comment by ericsnth** [comment]
> YahooData.fetch("TSLA", start="2000-01-01", end="2021-12-31")
> 
> I tried in python 2.7 and return 'TypeError: unbound method fetch() must be called with YahooData instance as first argument (got unicode instance instead)'
> 
> Do you know what changes needed for Python 2.7? I am in an old image in a cloud system and is hard for me to upgrade to python 3. Thanks

Hi, you can try with this code:
```
import io
import pandas
from datetime import datetime
import requests

class YahooData:
  def fetch(self, ticker, start, end):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9'
    }

    url = "https://query1.finance.yahoo.com/v7/finance/download/" + str(ticker)
    x = int(datetime.strptime(start, '%Y-%m-%d').strftime("%s"))
    y = int(datetime.strptime(end, '%Y-%m-%d').strftime("%s"))
    url += "?period1=" + str(x) + "&period2=" + str(y) + "&interval=1d&events=history&includeAdjustedClose=true"
    
    r = requests.get(url, headers=headers)
    pd = pandas.read_csv(io.StringIO(r.text), index_col=0, parse_dates=True)

    return pd

df = YahooData()
dfs = df.fetch("TSLA", start="2000-01-01", end="2021-12-31")
print(dfs)
```

Hopefully it can be useful, thanks :)

**Comment by bkcollection** [comment]
> > YahooData.fetch("TSLA", start="2000-01-01", end="2021-12-31")
> > I tried in python 2.7 and return 'TypeError: unbound method fetch() must be called with YahooData instance as first argument (got unicode instance instead)'
> > Do you know what changes needed for Python 2.7? I am in an old image in a cloud system and is hard for me to upgrade to python 3. Thanks
> 
> Hi, you can try with this code:
> 
> ```
> import io
> import pandas
> from datetime import datetime
> import requests
> 
> class YahooData:
>   def fetch(self, ticker, start, end):
>     headers = {
>         'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9'
>     }
> 
>     url = "https://query1.finance.yahoo.com/v7/finance/download/" + str(ticker)
>     x = int(datetime.strptime(start, '%Y-%m-%d').strftime("%s"))
>     y = int(datetime.strptime(end, '%Y-%m-%d').strftime("%s"))
>     url += "?period1=" + str(x) + "&period2=" + str(y) + "&interval=1d&events=history&includeAdjustedClose=true"
>     
>     r = requests.get(url, headers=headers)
>     pd = pandas.read_csv(io.StringIO(r.text), index_col=0, parse_dates=True)
> 
>     return pd
> 
> df = YahooData()
> dfs = df.fetch("TSLA", start="2000-01-01", end="2021-12-31")
> print(dfs)
> ```
> 
> Hopefully it can be useful, thanks :)

Thanks @ericsnth . This error exists ```
x = int(datetime.strptime(start, '%Y-%m-%d').strftime("%s"))
AttributeError: 'module' object has no attribute 'strptime'
```

**Comment by ericsnth** [comment]
> > > YahooData.fetch("TSLA", start="2000-01-01", end="2021-12-31")
> > > I tried in python 2.7 and return 'TypeError: unbound method fetch() must be called with YahooData instance as first argument (got unicode instance instead)'
> > > Do you know what changes needed for Python 2.7? I am in an old image in a cloud system and is hard for me to upgrade to python 3. Thanks
> > 
> > 
> > Hi, you can try with this code:
> > ```
> > import io
> > import pandas
> > from datetime import datetime
> > import requests
> > 
> > class YahooData:
> >   def fetch(self, ticker, start, end):
> >     headers = {
> >         'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9'
> >     }
> > 
> >     url = "https://query1.finance.yahoo.com/v7/finance/download/" + str(ticker)
> >     x = int(datetime.strptime(start, '%Y-%m-%d').strftime("%s"))
> >     y = int(datetime.strptime(end, '%Y-%m-%d').strftime("%s"))
> >     url += "?period1=" + str(x) + "&period2=" + str(y) + "&interval=1d&events=history&includeAdjustedClose=true"
> >     
> >     r = requests.get(url, headers=headers)
> >     pd = pandas.read_csv(io.StringIO(r.text), index_col=0, parse_dates=True)
> > 
> >     return pd
> > 
> > df = YahooData()
> > dfs = df.fetch("TSLA", start="2000-01-01", end="2021-12-31")
> > print(dfs)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hopefully it can be useful, thanks :)
> 
> Thanks @ericsnth . This error exists ```
> 
> ```
> x = int(datetime.strptime(start, '%Y-%m-%d').strftime("%s"))
> AttributeError: 'module' object has no attribute 'strptime'
> ```

make sure you have imported the datetime module in the following way:

```
from datetime import datetime
```

If I had to guess, you did this:
```
import datetime
```

if you import the datetime module only with 'import datetime', you can change the code with:

```
x = int(datetime.datetime.strptime(date, "%Y-%m-%d").strftime("%s"))

```

**Comment by bkcollection** [comment]
It works now. Thanks @ericsnth
